name: Don't Squash & Merge on `main`
on:
  pull_request:
    branches:
      - main
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: "Comment about squash & merge"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr comment $PR --body "
          # Create a merge commit

          ![Use **merge commit**](https://i.imgur.com/9vRccR6.jpg)

          Do not **Squash and merge** into `main`"
